# Generated by Django 4.1.4 on 2022-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('active', 'activated'), ('n-active', 'not activated'), ('over', 'overdue')], default='n-active', max_length=13),
        ),
    ]
