# Generated by Django 4.1.4 on 2022-12-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.AddField(
            model_name='card',
            name='_status',
            field=models.CharField(choices=[('active', 'активирована'), ('n-active', 'не активирована'), ('over', 'просрочена')], default='n-active', max_length=13),
        ),
    ]
